In [16]:
# check scikit-learn version
import sklearn
print(sklearn.__version__)

1.2.2

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_squared_error
import numpy as np
import pandas as pd
import pyodbc

In [18]:
serverName = "sqlserver-pw.database.windows.net" 
databaseName = "db-ai"
username = "girls"
password = "Password?"

In [19]:
cnxn = pyodbc.connect('DRIVER={SQL Server};SERVER='+serverName+';DATABASE='+databaseName+';UID='+username+';PWD='+ password)
cursor = cnxn.cursor()

In [20]:
query = "SELECT * FROM try.DatiConsumi_ML"

#Load the dataset into a pandas DataFrame
df = pd.read_sql(query, cnxn)

C:\Users\IreneDeNevi\AppData\Local\Temp\ipykernel_32508\4010930346.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, cnxn)

In [21]:
print(df.head(20))

   Canale CodAgenzia ClusterAgenzia CodContratto CategoriaCespite Cespite  \
0       6          1              1       203252                5       4
1       6          1              1       230585                5       4
2       6          1              1       230586                5       4
3       6          1              1       230588                5       4
4       6          1              1       230591                5       4
5       6          1              1       230592                5       4
6       6          1              1       230603                5       4
7       6          1              1       230605                5       4
8       6          1              1       230611                5       4
9       6          1              1       230618                5       4
10      6          1              1       230633                5       4
11      6          1              1       230636                5       4
12      6          1              1       230642                5       4
13      6          1              1       230662                5       4
14      6          1              1       230668                5       4
15      6          1              1       230672                5       4
16      6          1              1       230681                5       4
17      6          1              1       230687                5       4
18      6          1              1       230693                5       4
19      6          1              1       230702                5       4

   TipologiaUtenza DataTrasf.entr. DataTrasf.usc. MotivoBloccoCalc.  ...  \
0                3      2016-10-01     2017-08-31                16  ...
1                3      2017-01-01     2017-11-30                 3  ...
2                3      2017-01-01     2017-11-30                 3  ...
3                3      2017-01-01     2017-11-30                 3  ...
4                3      2017-01-01     2017-11-30                 3  ...
5                3      2017-01-01     2017-11-30                 3  ...
6                3      2017-01-01     2017-11-30                 3  ...
7                3      2017-01-01     2017-11-30                 3  ...
8                3      2017-01-01     2017-11-30                 3  ...
9                3      2017-01-01     2017-11-30                16  ...
10               3      2017-01-01     2017-11-30                 3  ...
11               3      2017-01-01     2017-11-30                 3  ...
12               3      2017-01-01     2017-11-30                 3  ...
13               3      2017-01-01     2017-11-30                 3  ...
14               3      2017-01-01     2017-11-30                16  ...
15               3      2017-01-01     2017-11-30                 3  ...
16               3      2017-01-01     2017-11-30                16  ...
17               3      2017-01-01     2017-11-30                 3  ...
18               3      2017-01-01     2017-11-30                 3  ...
19               3      2017-01-01     2017-11-30                 3  ...

   Mese55 Mese56 Mese57 Mese58 Mese59 Mese60 MesiBEP MesiAttivi UltimoReddito  \
0     NaN    NaN    NaN    NaN    NaN    NaN      11         11         -45.6
1     NaN    NaN    NaN    NaN    NaN    NaN      11         11         -44.1
2     NaN    NaN    NaN    NaN    NaN    NaN      11         11         -44.1
3     NaN    NaN    NaN    NaN    NaN    NaN      11         11         -44.1
4     NaN    NaN    NaN    NaN    NaN    NaN      11         11         -44.1
5     NaN    NaN    NaN    NaN    NaN    NaN      11         11         -44.1
6     NaN    NaN    NaN    NaN    NaN    NaN      11         11         -44.1
7     NaN    NaN    NaN    NaN    NaN    NaN      11         11         -44.1
8     NaN    NaN    NaN    NaN    NaN    NaN      11         11         -44.1
9     NaN    NaN    NaN    NaN    NaN    NaN      11         11         -45.6
10    NaN    NaN    NaN    NaN    NaN    NaN      11         11         -44.1
11    NaN    NaN    NaN    NaN    NaN    NaN      11         11         -44.1
12    NaN    NaN    NaN    NaN    NaN    NaN      11         11         -44.1
13    NaN    NaN    NaN    NaN    NaN    NaN      11         11         -44.1
14    NaN    NaN    NaN    NaN    NaN    NaN      11         11         -45.6
15    NaN    NaN    NaN    NaN    NaN    NaN      11         11         -44.1
16    NaN    NaN    NaN    NaN    NaN    NaN      11         11         -45.6
17    NaN    NaN    NaN    NaN    NaN    NaN      11         11         -44.1
18    NaN    NaN    NaN    NaN    NaN    NaN      11         11         -44.1
19    NaN    NaN    NaN    NaN    NaN    NaN      11         11         -44.1

   BEP
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
10   0
11   0
12   0
13   0
14   0
15   0
16   0
17   0
18   0
19   0

[20 rows x 98 columns]

In [22]:
df.columns

Index(['Canale', 'CodAgenzia', 'ClusterAgenzia', 'CodContratto',
       'CategoriaCespite', 'Cespite', 'TipologiaUtenza', 'DataTrasf.entr.',
       'DataTrasf.usc.', 'MotivoBloccoCalc.', 'Anagrafica',
       'SettoreMerceologico', 'ListinoProposto', 'Soc.Vend.Prec.',
       'ClusterSocVend', 'Localita', 'Cod.ISTAT', 'Provincia',
       'RegioneItaliana', 'Zona', 'ModoPagamento', 'Permanenza',
       'ConsumoMedio_annuo', 'ConsumoTotale', 'MargineFissoQF_annuo',
       'MargineFissoTotale', 'MargineVariabileQV', 'MargineVariabileQV_annuo',
       'MargineVariabileTotale', 'MargineTotale', 'Provvigioni',
       'Acquisizione', 'CostoAnnuo_Post-vendita_Customer-care',
       'RedditoTotale', 'Mese01', 'Mese02', 'Mese03', 'Mese04', 'Mese05',
       'Mese06', 'Mese07', 'Mese08', 'Mese09', 'Mese10', 'Mese11', 'Mese12',
       'Mese13', 'Mese14', 'Mese15', 'Mese16', 'Mese17', 'Mese18', 'Mese19',
       'Mese20', 'Mese21', 'Mese22', 'Mese23', 'Mese24', 'Mese25', 'Mese26',
       'Mese27', 'Mese28', 'Mese29', 'Mese30', 'Mese31', 'Mese32', 'Mese33',
       'Mese34', 'Mese35', 'Mese36', 'Mese37', 'Mese38', 'Mese39', 'Mese40',
       'Mese41', 'Mese42', 'Mese43', 'Mese44', 'Mese45', 'Mese46', 'Mese47',
       'Mese48', 'Mese49', 'Mese50', 'Mese51', 'Mese52', 'Mese53', 'Mese54',
       'Mese55', 'Mese56', 'Mese57', 'Mese58', 'Mese59', 'Mese60', 'MesiBEP',
       'MesiAttivi', 'UltimoReddito', 'BEP'],
      dtype='object')

In [23]:
df = df.drop(['Mese01', 'Mese02', 'Mese03', 'Mese04', 'Mese05',
       'Mese06', 'Mese07', 'Mese08', 'Mese09', 'Mese10', 'Mese11', 'Mese12',
       'Mese13', 'Mese14', 'Mese15', 'Mese16', 'Mese17', 'Mese18', 'Mese19',
       'Mese20', 'Mese21', 'Mese22', 'Mese23', 'Mese24', 'Mese25', 'Mese26',
       'Mese27', 'Mese28', 'Mese29', 'Mese30', 'Mese31', 'Mese32', 'Mese33',
       'Mese34', 'Mese35', 'Mese36', 'Mese37', 'Mese38', 'Mese39', 'Mese40',
       'Mese41', 'Mese42', 'Mese43', 'Mese44', 'Mese45', 'Mese46', 'Mese47',
       'Mese48', 'Mese49', 'Mese50', 'Mese51', 'Mese52', 'Mese53', 'Mese54',
       'Mese55', 'Mese56', 'Mese57', 'Mese58', 'Mese59', 'Mese60', 'DataTrasf.entr.',
       'DataTrasf.usc.'], axis=1)

In [24]:
df

,Canale,CodAgenzia,ClusterAgenzia,CodContratto,CategoriaCespite,Cespite,TipologiaUtenza,MotivoBloccoCalc.,Anagrafica,SettoreMerceologico,...,MargineVariabileTotale,MargineTotale,Provvigioni,Acquisizione,CostoAnnuo_Post-vendita_Customer-care,RedditoTotale,MesiBEP,MesiAttivi,UltimoReddito,BEP
0,6,1,1,203252,5,4,3,16,52,1,...,11.53,121.34,111.99,17.35,13.33,-45.71,11,11,-45.6,0
1,6,1,1,230585,5,4,3,3,57,1,...,11.50,120.97,111.99,15.85,13.33,-44.46,11,11,-44.1,0
2,6,1,1,230586,5,4,3,3,5,1,...,11.50,120.97,111.99,15.85,13.33,-44.46,11,11,-44.1,0
3,6,1,1,230588,5,4,3,3,44,1,...,11.50,120.97,111.99,15.85,13.33,-44.46,11,11,-44.1,0
4,6,1,1,230591,5,4,3,3,44,1,...,11.50,120.97,111.99,15.85,13.33,-44.46,11,11,-44.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474952,4,1,1,349922,2,2,1,8,33,2,...,3.95,50.41,100.84,10.37,13.33,-86.97,7,7,-85.7,0
474953,4,1,2,432128,3,3,2,8,97,2,...,29.19,97.90,100.84,10.37,12.06,-39.65,7,7,-38.3,0
474954,4,1,3,389387,2,2,1,16,56,2,...,4.15,52.91,100.84,11.87,13.33,-87.27,7,7,-87.2,0
474955,4,1,2,433322,3,3,2,16,62,2,...,29.75,99.78,100.84,11.87,12.06,-39.78,7,7,-39.8,0
474956,4,1,1,164621,5,4,3,16,89,1,...,2.07,21.80,106.47,11.87,13.33,-103.32,2,2,-103.1,0

In [25]:
from sklearn.datasets import make_regression
# create datasets
y = df[['MesiAttivi', 'RedditoTotale', 'BEP']]                                         #Targets
X = df[[i for i in list(df.columns) if i != 'RedditoTotale' or 'MesiAttivi' or 'BEP']] #features
# summarize dataset
print(X.shape, y.shape)

(474957, 36) (474957, 3)

In [26]:
X

,Canale,CodAgenzia,ClusterAgenzia,CodContratto,CategoriaCespite,Cespite,TipologiaUtenza,MotivoBloccoCalc.,Anagrafica,SettoreMerceologico,...,MargineVariabileTotale,MargineTotale,Provvigioni,Acquisizione,CostoAnnuo_Post-vendita_Customer-care,RedditoTotale,MesiBEP,MesiAttivi,UltimoReddito,BEP
0,6,1,1,203252,5,4,3,16,52,1,...,11.53,121.34,111.99,17.35,13.33,-45.71,11,11,-45.6,0
1,6,1,1,230585,5,4,3,3,57,1,...,11.50,120.97,111.99,15.85,13.33,-44.46,11,11,-44.1,0
2,6,1,1,230586,5,4,3,3,5,1,...,11.50,120.97,111.99,15.85,13.33,-44.46,11,11,-44.1,0
3,6,1,1,230588,5,4,3,3,44,1,...,11.50,120.97,111.99,15.85,13.33,-44.46,11,11,-44.1,0
4,6,1,1,230591,5,4,3,3,44,1,...,11.50,120.97,111.99,15.85,13.33,-44.46,11,11,-44.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474952,4,1,1,349922,2,2,1,8,33,2,...,3.95,50.41,100.84,10.37,13.33,-86.97,7,7,-85.7,0
474953,4,1,2,432128,3,3,2,8,97,2,...,29.19,97.90,100.84,10.37,12.06,-39.65,7,7,-38.3,0
474954,4,1,3,389387,2,2,1,16,56,2,...,4.15,52.91,100.84,11.87,13.33,-87.27,7,7,-87.2,0
474955,4,1,2,433322,3,3,2,16,62,2,...,29.75,99.78,100.84,11.87,12.06,-39.78,7,7,-39.8,0
474956,4,1,1,164621,5,4,3,16,89,1,...,2.07,21.80,106.47,11.87,13.33,-103.32,2,2,-103.1,0

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=42)

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
model = LinearRegression()

In [30]:
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values